package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/adityasingh/svenska/api/internal/db"
)

// importFromPostgres copies an existing Postgres database into SQLite.
//
// One-shot, for the migration off Postgres. Without it the switch would
// discard listening progress and vocabulary history, which are the only data
// here that cannot be regenerated by re-running ingestion.
func importFromPostgres(ctx context.Context, conn *sql.DB, pgURL string) error {
	pgc, err := pgx.Connect(ctx, pgURL)
	if err != nil {
		return fmt.Errorf("connect postgres: %w", err)
	}
	defer pgc.Close(ctx)

	// Sources are seeded by migration, so map Postgres ids onto the ids the
	// SQLite seed produced rather than inserting duplicates.
	sourceIDs := map[int]int{}
	rows, err := pgc.Query(ctx, `SELECT id, slug FROM sources`)
	if err != nil {
		return err
	}
	for rows.Next() {
		var id int
		var slug string
		if err := rows.Scan(&id, &slug); err != nil {
			rows.Close()
			return err
		}
		var localID int
		if err := conn.QueryRowContext(ctx,
			`SELECT id FROM sources WHERE slug = ?`, slug).Scan(&localID); err != nil {
			log.Printf("pg-import: no local source %q, skipping its items", slug)
			continue
		}
		sourceIDs[id] = localID
	}
	rows.Close()

	itemIDs := map[int]int{}
	rows, err = pgc.Query(ctx, `
		SELECT id, source_id, external_id, title, COALESCE(description,''),
		       published_at, COALESCE(audio_url,''), COALESCE(audio_path,''),
		       COALESCE(duration_ms,0), status
		FROM items ORDER BY id`)
	if err != nil {
		return err
	}
	type item struct {
		id, sourceID        int
		extID, title, desc  string
		published           *time.Time
		audioURL, audioPath string
		durationMS          int
		status              string
	}
	var items []item
	for rows.Next() {
		var it item
		if err := rows.Scan(&it.id, &it.sourceID, &it.extID, &it.title, &it.desc,
			&it.published, &it.audioURL, &it.audioPath, &it.durationMS, &it.status); err != nil {
			rows.Close()
			return err
		}
		items = append(items, it)
	}
	rows.Close()

	for _, it := range items {
		local, ok := sourceIDs[it.sourceID]
		if !ok {
			continue
		}
		var pub any
		if it.published != nil {
			pub = db.FormatTime(*it.published)
		}
		var newID int
		err := conn.QueryRowContext(ctx, `
			INSERT INTO items (source_id, external_id, title, description,
			                   published_at, audio_url, audio_path, duration_ms, status)
			VALUES (?,?,?,?,?,?,?,?,?)
			ON CONFLICT (source_id, external_id) DO UPDATE SET status = excluded.status
			RETURNING id`,
			local, it.extID, it.title, it.desc, pub,
			nullIfEmpty(it.audioURL), nullIfEmpty(it.audioPath), it.durationMS, it.status,
		).Scan(&newID)
		if err != nil {
			return fmt.Errorf("item %d: %w", it.id, err)
		}
		itemIDs[it.id] = newID
	}
	log.Printf("pg-import: %d items", len(itemIDs))

	// Segments and tokens are regenerable from the audio, but re-transcribing
	// is the slow step, so carry them across.
	segIDs := map[int]int{}
	rows, err = pgc.Query(ctx,
		`SELECT id, item_id, idx, start_ms, end_ms, text FROM segments ORDER BY id`)
	if err != nil {
		return err
	}
	type seg struct {
		id, itemID, idx, start, end int
		text                        string
	}
	var segs []seg
	for rows.Next() {
		var sg seg
		if err := rows.Scan(&sg.id, &sg.itemID, &sg.idx, &sg.start, &sg.end, &sg.text); err != nil {
			rows.Close()
			return err
		}
		segs = append(segs, sg)
	}
	rows.Close()

	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	for _, sg := range segs {
		local, ok := itemIDs[sg.itemID]
		if !ok {
			continue
		}
		var newID int
		if err := tx.QueryRowContext(ctx, `
			INSERT INTO segments (item_id, idx, start_ms, end_ms, text)
			VALUES (?,?,?,?,?)
			ON CONFLICT (item_id, idx) DO UPDATE SET text = excluded.text
			RETURNING id`, local, sg.idx, sg.start, sg.end, sg.text).Scan(&newID); err != nil {
			tx.Rollback()
			return err
		}
		segIDs[sg.id] = newID
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	log.Printf("pg-import: %d segments", len(segIDs))

	if err := copyTokens(ctx, pgc, conn, itemIDs, segIDs); err != nil {
		return err
	}
	if err := copyUserData(ctx, pgc, conn, itemIDs); err != nil {
		return err
	}
	log.Println("pg-import: done")
	return nil
}

func copyTokens(ctx context.Context, pgc *pgx.Conn, conn *sql.DB,
	itemIDs, segIDs map[int]int) error {

	rows, err := pgc.Query(ctx, `
		SELECT item_id, segment_id, idx, surface, normalized,
		       start_ms, end_ms, is_word, COALESCE(lemma,'')
		FROM tokens ORDER BY item_id, idx`)
	if err != nil {
		return err
	}
	defer rows.Close()

	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback() //nolint:errcheck

	stmt, err := tx.PrepareContext(ctx, `
		INSERT INTO tokens (item_id, segment_id, idx, surface, normalized,
		                    start_ms, end_ms, is_word, lemma)
		VALUES (?,?,?,?,?,?,?,?,?)
		ON CONFLICT (item_id, idx) DO NOTHING`)
	if err != nil {
		return err
	}
	defer stmt.Close()

	n := 0
	for rows.Next() {
		var itemID, segID, idx, start, end int
		var surface, norm, lemma string
		var isWord bool
		if err := rows.Scan(&itemID, &segID, &idx, &surface, &norm,
			&start, &end, &isWord, &lemma); err != nil {
			return err
		}
		li, ok1 := itemIDs[itemID]
		ls, ok2 := segIDs[segID]
		if !ok1 || !ok2 {
			continue
		}
		if _, err := stmt.ExecContext(ctx, li, ls, idx, surface, norm,
			start, end, boolToInt(isWord), nullIfEmpty(lemma)); err != nil {
			return err
		}
		n++
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	log.Printf("pg-import: %d tokens", n)
	return nil
}

// copyUserData carries the things that cannot be regenerated: what you have
// listened to, and which words you have looked up or marked.
func copyUserData(ctx context.Context, pgc *pgx.Conn, conn *sql.DB, itemIDs map[int]int) error {
	rows, err := pgc.Query(ctx,
		`SELECT item_id, position_ms, completed, listen_count FROM progress`)
	if err != nil {
		return err
	}
	progress := 0
	for rows.Next() {
		var itemID, pos, count int
		var completed bool
		if err := rows.Scan(&itemID, &pos, &completed, &count); err != nil {
			rows.Close()
			return err
		}
		local, ok := itemIDs[itemID]
		if !ok {
			continue
		}
		if _, err := conn.ExecContext(ctx, `
			INSERT INTO progress (item_id, position_ms, completed, listen_count)
			VALUES (?,?,?,?)
			ON CONFLICT (item_id) DO UPDATE SET
			  position_ms = excluded.position_ms,
			  completed = excluded.completed,
			  listen_count = excluded.listen_count`,
			local, pos, boolToInt(completed), count); err != nil {
			rows.Close()
			return err
		}
		progress++
	}
	rows.Close()
	log.Printf("pg-import: %d progress rows", progress)

	rows, err = pgc.Query(ctx, `
		SELECT COALESCE(language_code,'sv'), lemma, status, lookup_count,
		       first_seen, last_seen
		FROM user_words`)
	if err != nil {
		return err
	}
	defer rows.Close()
	words := 0
	for rows.Next() {
		var lang, lemma, status string
		var count int
		var first, last time.Time
		if err := rows.Scan(&lang, &lemma, &status, &count, &first, &last); err != nil {
			return err
		}
		if _, err := conn.ExecContext(ctx, `
			INSERT INTO user_words (language_code, lemma, status, lookup_count, first_seen, last_seen)
			VALUES (?,?,?,?,?,?)
			ON CONFLICT (language_code, lemma) DO UPDATE SET
			  status = excluded.status,
			  lookup_count = excluded.lookup_count,
			  last_seen = excluded.last_seen`,
			lang, lemma, status, count, db.FormatTime(first), db.FormatTime(last)); err != nil {
			return err
		}
		words++
	}
	log.Printf("pg-import: %d vocabulary rows", words)
	return nil
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func nullIfEmpty(s string) any {
	if s == "" {
		return nil
	}
	return s
}
